apiVersion: v1
kind: PersistentVolume
metadata:
   name: eszoovol02
spec:
   capacity:
     storage: 2Gi
   accessModes:
     - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   nfs:
     path: /export/files/eszoovol02
     server: 10.186.197.11

