#!/bin/bash

mkdir -p /export/files
cd /export/files
git clone https://github.com/jfosHELM/es-demo.git
mkdir eskafvol01  eskafvol02  eskafvol03  eszoovol01  eszoovol02  eszoovol03
chown -R nobody:nogroup eskafvol01  eskafvol02  eskafvol03  eszoovol01  eszoovol02  eszoovol03
for i in $(ls es-demo/*yaml); do  kubectl create -f es-demo/$i; done

